apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-java-demo
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-java-demo
  template:
    metadata:
      labels:
        app: jenkins-java-demo
    spec:
      containers:
      - name: jenkins-java-demo
        image: registry.cn-hangzhou.aliyuncs.com/2dfire/springboot-helloworld:0.0.1 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-java-demo
  namespace: ci
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: jenkins-java-demo
  selector:
    app: jenkins-java-demo
  type: LoadBalancer
